[versions]
agp = "8.1.0"
androidx-test-ext-junit = "1.1.5"
androidxFragment = "1.6.1"
androidxLifecycle = "2.6.2"
appcompat = "1.6.1"
bindable = "1.1.0"
bundler = "1.0.4"
core-ktx = "1.9.0"
espresso-core = "3.5.1"
glide = "4.16.0"
junit = "4.13.2"
koin = "3.4.0"
kotlin = "1.8.0"
ksp = "1.8.10-1.0.9"
material = "1.10.0"
moshi = "1.15.0"
recyclerView = "1.3.2"
retrofit = "2.9.0"
sandwich = "1.3.9"
whatif = "1.1.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }


[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }


#Android X
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }

#KOIN
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin_android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

#NETWORK
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

sandwich = { module = "com.github.skydoves:sandwich", version.ref = "sandwich" }
ksp = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "ksp" }

bindables = { module = "com.github.skydoves:bindables", version.ref = "bindable" }
whatIf = { module = "com.github.skydoves:whatif", version.ref = "whatif" }
bundler = { module = "com.github.skydoves:bundler", version.ref = "bundler" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

#Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

